// next/with-cypress-app/app/form/page.tsx
"use client";
import { useState } from "react";

function Form() {
  const [status, setStatus] = useState<string>("");
  return (
    <>
      <label htmlFor="username-input">Username</label>
      <input id="username-input" />
      <button
        onClick={() => {
          const username = (
            document.getElementById("username-input") as HTMLInputElement
          ).value;
          if (!username) {
            setStatus("用户名不能为空");
            return;
          }
          setStatus("提交成功");
        }}
      >
        提交
      </button>
      <span>{status}</span>
    </>
  );
}

export default Form;

// vue/vue-with-vitest/src/views/Form.vue
<template>
    <div class="form">
        <h1>This is an form page</h1>
        <div>
            <label htmlFor="username-input">Username</label>
            <input id="username-input" v-model="input" />
            <button @click="handleClick">
                提交
            </button>
            <span>{{ status }}</span>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const status = ref('')
const input = ref('')
const handleClick = () => {
    const username = input.value;
    if (!username) {
        status.value = "用户名不能为空"
        return
    }
    status.value = "提交成功"
}
</script>

<style></style>
